spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: jrr
    password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderNotificationRequest:org.ecommerce.order.notification.OrderNotificationRequest

application:
  feign:
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments
    customer-url: http://localhost:8222/api/v1/customers
    discount-url: http://localhost:8222/api/v1/discounts
    cart-url: http://localhost:8222/api/v1/carts

server:
  port: 8050