spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: jrr
    password: admin
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentNotificationRequest:org.ecommerce.payment.notification.PaymentNotificationRequest

server:
  port: 8060