services:
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_USER: jrr
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongo_express
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #   networks:
  #     - backend

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   depends_on:
  #     - postgres
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_REPLICA_FETCH_MIN_BYTES: 1
      KAFKA_REPLICA_FETCH_WAIT_MAX_MS: 100
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - "9094:9094"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - backend

#  keycloak:
#    image: quay.io/keycloak/keycloak:latest
#    container_name: keycloak
#    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: admin
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
#      KC_DB_USERNAME: jrr
#      KC_DB_PASSWORD: admin
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    volumes:
#      - keycloak_data:/opt/keycloak/data
#    networks:
#      - backend

volumes:
  postgres_data:
  mongo_data:
  keycloak_data:

networks:
  backend:
    driver: bridge